<a href="https://colab.research.google.com/github/helango-seabiscuit/colab/blob/main/Linear_Algebra_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import scipy.linalg
from scipy.linalg import toeplitz

import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')
plt.rcParams.update({'font.size':14})

In [ ]:
M = np.arange(12).reshape(3,4)
print(M)
print("The matrix element at index (2,4) is ",M[1,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The matrix element at index (2,4) is  7


In [ ]:
C = np.arange(100).reshape(10,10)
CP = np.zeros(100).reshape(10,10)
print(C)
C1 = C[0:5,0:5]
C2 = C[0:5,5:]
C3 = C[5:,0:5]
C4 = C[5:,5:]
CP[0:5,0:5] = C4
CP[0:5,5:]=C3
CP[5:,0:5] = C2
CP[5:,5:]= C1
print(CP)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[55. 56. 57. 58. 59. 50. 51. 52. 53. 54.]
 [65. 66. 67. 68. 69. 60. 61. 62. 63. 64.]
 [75. 76. 77. 78. 79. 70. 71. 72. 73. 74.]
 [85. 86. 87. 88. 89. 80. 81. 82. 83. 84.]
 [95. 96. 97. 98. 99. 90. 91. 92. 93. 94.]
 [ 5.  6.  7.  8.  9.  0.  1.  2.  3.  4.]
 [15. 16. 17. 18. 19. 10. 11. 12. 13. 14.]
 [25. 26. 27. 28. 29. 20. 21. 22. 23. 24.]
 [35. 36. 37. 38. 39. 30. 31. 32. 33. 34.]
 [45. 46. 47. 48. 49. 40. 41. 42. 43. 44.]]


In [ ]:
C = np.arange(12).reshape(4,3)
D = np.arange(12).reshape(4,3)
R = np.zeros(12).reshape(4,3)
print(C)
print(D)
for i in range(C.shape[0]):
   for j in range(C.shape[1]):
     R[i,j] = C[i,j]+D[i,j]
print(R)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]
 [18. 20. 22.]]


In [ ]:
A = np.random.randn(3,4)
B = np.random.randn(3,4)
s = np.random.randn()

expr1 = s*(A+B)
expr2 = s*A+s*B
expr3 = A*s+B*s
print(np.round(2*expr3-expr1-expr2))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0. -0.]
 [ 0.  0.  0.  0.]]


In [ ]:
A = np.random.randn(4,4)
B = np.random.randn(4,4)
# print(A)
# print(B)
shapeA = A.shape
shapeB = B.shape

if shapeA[1] != shapeB[0]:
   print("invalid matrices for multiplication")
C = np.zeros((shapeA[0],shapeB[1]))
for i in range(shapeA[0]):
  for j in range(shapeB[1]):
    k = shapeA[1]
    for z in range(k):
      C[i,j] += A[i,z]*B[z,j]

D = A@B
print(C)
print(D)
np.isclose(C,D)

[[ 0.08700611  0.28932256 -0.22931998  0.03291228]
 [-1.42434367 -0.38740878 -0.57914928 -1.12626728]
 [-2.40071278 -0.59011579  0.08352494  0.34481076]
 [-1.40425467  0.01499989  0.44547465  1.73941546]]
[[ 0.08700611  0.28932256 -0.22931998  0.03291228]
 [-1.42434367 -0.38740878 -0.57914928 -1.12626728]
 [-2.40071278 -0.59011579  0.08352494  0.34481076]
 [-1.40425467  0.01499989  0.44547465  1.73941546]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
L = np.random.randn(2,6)
I = np.random.randn(6,3)
V = np.random.randn(3,5)
E = np.random.randn(5,2)

lm = (L@I@V@E).T
print(lm)

Lt = L.T
It = I.T
Vt = V.T
Et = E.T

# rmnoReverse = Lt@It@Vt@Et
rmreverse = Et@Vt@It@Lt
print(rmreverse)

[[ 0.38324582  2.66354194]
 [ 3.95931041 -0.54033746]]
[[ 0.38324582  2.66354194]
 [ 3.95931041 -0.54033746]]


In [ ]:
def isSymmetric(v):
  if v.shape[0] != v.shape[1]:
    return False

  for i in range(v.shape[0]):
    for j in range(v.shape[0]):
      if np.isclose(v[i,j], v[j,i]) == False:
        return False
  return True

V = np.random.randn(4,4)
Vt = V.T@V

print(isSymmetric(V))
print(isSymmetric(Vt))


False
True


In [ ]:
a = np.random.randn(4,4)
ata = (a+ a.T) / 2
isSymmetric(ata)

True

In [ ]:
d1 = np.diag(np.random.randn(5))
d2 = np.diag(np.random.randn(5))

r1 = d1*d2
r2 = d1@d2
r1-r2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n = 4
O = np.ones((n,n))
D = np.diag(np.arange(1,n+1)**2)
S = np.sqrt(D)

pre = D@O
pst = O@D
both = S@O@S

print('Ones matrix:')
print(O), print(' ')

print('Diagonal matrix: ')
print(D), print(' ')

print('Sqrt-diagonal matrix: ')
print(S), print(' ')

print('Pre-multiply by diagonal:')
print(pre), print(' ')

print('Post-multiply by diagonal: ')
print(pst),print(' ')

print('Pre- and post-multiply by sqrt-diagonal:')
print(both)


Ones matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 
Diagonal matrix: 
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
 
Sqrt-diagonal matrix: 
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
 
Pre-multiply by diagonal:
[[ 1.  1.  1.  1.]
 [ 4.  4.  4.  4.]
 [ 9.  9.  9.  9.]
 [16. 16. 16. 16.]]
 
Post-multiply by diagonal: 
[[ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]]
 
Pre- and post-multiply by sqrt-diagonal:
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]
